# Generated by Django 4.0.1 on 2022-01-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registration_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='registration_data',
            new_name='registration_attributes',
        ),
        migrations.AddField(
            model_name='event',
            name='submission_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
