# Generated by Django 4.0.1 on 2022-01-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('core', 'Core'), ('core-support', 'Core Support'), ('web', 'Web Dev'), ('design', 'Design'), ('video-editing', 'Video Editing'), ('pr', 'PR'), ('gaming', 'Gaming')], max_length=100)),
                ('role', models.CharField(choices=[('President', 'President'), ('Student Convenor', 'Student Convenor'), ('Technical Lead', 'Technical Lead'), ('Technical Co-Lead', 'Technical Co-Lead'), ('Convenor', 'Convenor'), ('Head', 'Head'), ('Co-Head', 'Co-Head'), ('Member', 'Member')], max_length=100)),
                ('profilepic', models.ImageField(blank=True, upload_to='team-profilepics')),
                ('portfolio', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('dribbble', models.URLField(blank=True)),
            ],
        ),
    ]
