# Generated by Django 4.0.2 on 2022-02-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profilepic',
            field=models.URLField(blank=True),
        ),
    ]
