# Generated by Django 4.0.3 on 2022-03-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Professor In Charge', 'Professor In Charge'), ('Technical Lead', 'Technical Lead'), ('Convenor', 'Convenor'), ('Head', 'Head'), ('Co-Head', 'Co-Head'), ('Member', 'Member')], max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(choices=[('core', 'Core'), ('core-support', 'Core Support'), ('web', 'Web Dev'), ('design', 'Design'), ('video-editing', 'Video Editing'), ('pr', 'PR'), ('gaming', 'Gaming'), ('sponsorship', 'Sponsorship')], max_length=100),
        ),
    ]
