# Generated by Django 4.0.3 on 2022-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='degree',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=1000, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='institute_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=1000, verbose_name='last name'),
        ),
    ]
