# Generated by Django 4.0.2 on 2022-02-28 15:59

import api.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, upload_to='docs')),
            ],
        ),
        migrations.CreateModel(
            name='ProofPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, storage=api.storage_backends.PrivateMediaStorage(), upload_to='')),
            ],
        ),
    ]
