# Generated by Django 4.0.1 on 2022-02-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='name',
        ),
        migrations.AddField(
            model_name='pdf',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='docs'),
        ),
    ]
