# Generated by Django 4.0.2 on 2022-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, upload_to='docs')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='name',
        ),
        migrations.AddField(
            model_name='pdf',
            name='title',
            field=models.CharField(default='ggg', max_length=255),
            preserve_default=False,
        ),
    ]
