# Generated by Django 4.0.2 on 2022-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_remove_pdf_name_pdf_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, upload_to='docs')),
            ],
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='email',
            new_name='name',
        ),
    ]
