# Generated by Django 4.0.2 on 2022-02-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_proofpdf_rename_email_pdf_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='name',
            new_name='title',
        ),
    ]
