# Generated by Django 4.0.1 on 2022-01-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamparticipation',
            old_name='team_creator',
            new_name='team_captain',
        ),
        migrations.RemoveField(
            model_name='teamparticipation',
            name='registration_data',
        ),
    ]
