# Generated by Django 4.0.1 on 2022-01-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('registration', '0002_teammember_registration_data_teamparticipation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamparticipation',
            name='team_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_creator_acc', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='team_name',
            field=models.CharField(default='default_team_name', max_length=52),
            preserve_default=False,
        ),
    ]
